# Detect host OS to select the right vendored DuckDB library.
# rpath is relative to the binary (build/markov), so renaming or moving the
# repo doesn't break the libduckdb.so lookup.
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
	LIBDIR := $(CURDIR)/libs/macos
	RPATH  := @loader_path/../libs/macos
else
	LIBDIR := $(CURDIR)/libs/linux
	RPATH  := $$ORIGIN/../libs/linux
endif

CFLAGS := -Wall -Wextra -O2 -I$(LIBDIR) -Ibuild
LDFLAGS := -L$(LIBDIR) -lduckdb -Wl,-rpath,'$(RPATH)'
BIN := build/markov
SQL := schema.sql train_stage.sql train_order.sql

all: $(BIN)

# Embed the SQL templates as C string literals so the binary is
# self-contained (no .sql files needed next to the executable).
build/sql_embed.h: $(SQL)
	mkdir -p build
	@{ echo '/* generated by make from *.sql — do not edit */'; \
	for f in $(SQL); do \
		printf 'static const char %s[] =\n' "$$(basename $$f .sql)_sql"; \
		sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/    "/' -e 's/$$/\\n"/' $$f; \
		printf ';\n'; \
	done; } > $@

$(BIN): markov.c markov_utils.h build/sql_embed.h
	gcc $(CFLAGS) -o $(BIN) markov.c $(LDFLAGS)

run: $(BIN)
	./$(BIN)

demo: $(BIN)
	rm -f data/db/demo.db data/db/demo.db.wal
	./$(BIN) data/db/demo.db < demo.txt

debug: build/sql_embed.h
	gcc -g $(CFLAGS) -o $(BIN) markov.c $(LDFLAGS) && lldb ./$(BIN)

clean:
	rm -rf build
