/* markov.c — DuckDB-backed multi-order Markov text engine.
 * The model lives entirely in the database; this file is a thin driver:
 * REPL, training driver (SQL templates), backoff generation loop, stats. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <time.h>
#include <sys/stat.h>
#include "duckdb.h"

#define MARKOV_UTILS_IMPLEMENTATION
#include "markov_utils.h"
#include "sql_embed.h"   /* generated by make from *.sql — schema_sql etc. */

#define MAX_ORDER   9
#define MAX_HISTORY (1 << 20)
#define BUF         8192

/* ---------------- DB helpers ---------------- */

static int db_exec(duckdb_connection con, const char *sql) {
    duckdb_result r;
    if (duckdb_query(con, sql, &r) == DuckDBError) {
        fprintf(stderr, "%s[SQL ERROR]%s %s\n", RED, RESET, duckdb_result_error(&r));
        duckdb_destroy_result(&r);
        return 1;
    }
    duckdb_destroy_result(&r);
    return 0;
}

static void print_result(duckdb_result *r) {
    idx_t nc = duckdb_column_count(r), nr = duckdb_row_count(r);
    if (nc == 0) return;
    /* materialize header + cells; numbers right-align */
    char **cell = malloc(sizeof(char *) * nc * (nr + 1));
    int   *num  = calloc(nc, sizeof *num);
    for (idx_t c = 0; c < nc; c++) {
        duckdb_type t = duckdb_column_type(r, c);
        num[c]  = (t >= DUCKDB_TYPE_TINYINT && t <= DUCKDB_TYPE_DOUBLE) ||
                  t == DUCKDB_TYPE_HUGEINT || t == DUCKDB_TYPE_DECIMAL;
        cell[c] = strdup(duckdb_column_name(r, c));
    }
    for (idx_t row = 0; row < nr; row++)
        for (idx_t c = 0; c < nc; c++) {
            char *v = duckdb_value_varchar(r, c, row);
            cell[(row + 1) * nc + c] = strdup(v ? v : "-");
            duckdb_free(v);
        }
    mu_print_table(cell, nc, nr, num);
    for (idx_t i = 0; i < nc * (nr + 1); i++) free(cell[i]);
    free(cell); free(num);
}

static void run_and_print(duckdb_connection con, const char *sql) {
    duckdb_result r;
    if (duckdb_query(con, sql, &r) == DuckDBError)
        fprintf(stderr, "[SQL ERROR] %s\n", duckdb_result_error(&r));
    else
        print_result(&r);
    duckdb_destroy_result(&r);
}

static long query_long(duckdb_connection con, const char *sql) {
    duckdb_result r;
    long v = -1;
    if (duckdb_query(con, sql, &r) != DuckDBError && duckdb_row_count(&r) > 0)
        v = (long)duckdb_value_int64(&r, 0, 0);
    duckdb_destroy_result(&r);
    return v;
}

/* ---------------- :train ---------------- */

static void cmd_train(duckdb_connection con, const char *path, int k) {
    if (k < 1 || k > MAX_ORDER) { fprintf(stderr, "order must be 1..%d\n", MAX_ORDER); return; }
    /* read_text() returns 0 rows for a missing file instead of erroring,
     * which would silently record a 0-token training run */
    struct stat st;
    if (stat(path, &st) != 0) {
        fprintf(stderr, "%scannot find %s%s — paths are relative to the working directory\n",
                RED, path, RESET);
        return;
    }

    char *esc   = mu_str_replace(path, "'", "''");
    char *stage = mu_str_replace(train_stage_sql, "{{PATH}}", esc);
    double t0   = mu_now_sec();
    if (db_exec(con, stage) == 0) {
        /* train every order 1..k so backoff never hits an untrained order */
        for (int ord = 1; ord <= k; ord++) {
            char kbuf[8], kmbuf[8];
            snprintf(kbuf, sizeof kbuf, "%d", ord);
            snprintf(kmbuf, sizeof kmbuf, "%d", ord - 1);
            char *s1 = mu_str_replace(train_order_sql, "{{K}}", kbuf);
            char *s2 = mu_str_replace(s1, "{{KM1}}", kmbuf);
            if (db_exec(con, s2)) { free(s1); free(s2); break; }
            free(s1); free(s2);
        }
        printf("trained %s — %ld tokens staged in %.2fs, n-grams merged per order:\n",
               path, query_long(con, "SELECT COUNT(*) FROM doc_tokens"),
               mu_now_sec() - t0);
        run_and_print(con,
            "SELECT ord AS \"order\", ngrams_added FROM training_runs"
            " WHERE document_id = currval('seq_doc') ORDER BY ord");
    }
    free(esc); free(stage);
}

/* ---------------- :gen ----------------
 * Hybrid: one set-based SELECT loads the model into sorted arrays, the random
 * walk runs at RAM speed, and the step log is bulk-appended afterwards.
 * DuckDB stays the system of record; both ends of the loop are batched. */

typedef struct { char *token; int next_id; long count; } MRow;
typedef struct { int ord; char *state; long first; int n; long total; } MGroup;
typedef struct { MRow *rows; MGroup *grp; long nrows, ngrp, bytes; } Model;

static Model model_load(duckdb_connection con) {
    Model m = {0};
    duckdb_result r;
    if (duckdb_query(con,
            "SELECT t.ord, t.state_key, v.token, t.next_id, t.count "
            "FROM transitions t JOIN vocabulary v ON v.id = t.next_id "
            "ORDER BY t.ord, t.state_key", &r) == DuckDBError) {
        fprintf(stderr, "%s[SQL ERROR]%s %s\n", RED, RESET, duckdb_result_error(&r));
        duckdb_destroy_result(&r);
        return m;
    }
    m.nrows = (long)duckdb_row_count(&r);
    m.rows  = malloc((size_t)m.nrows * sizeof *m.rows);
    m.grp   = malloc((size_t)m.nrows * sizeof *m.grp);
    m.bytes = m.nrows * (long)(sizeof *m.rows + sizeof *m.grp);
    for (long i = 0; i < m.nrows; i++) {
        int   ord   = (int)duckdb_value_int64(&r, 0, i);
        char *state = duckdb_value_varchar(&r, 1, i);
        char *tok   = duckdb_value_varchar(&r, 2, i);
        m.rows[i].token   = strdup(tok);
        m.rows[i].next_id = (int)duckdb_value_int64(&r, 3, i);
        m.rows[i].count   = (long)duckdb_value_int64(&r, 4, i);
        m.bytes += (long)strlen(tok) + 1;
        if (m.ngrp == 0 || ord != m.grp[m.ngrp - 1].ord ||
            strcmp(state, m.grp[m.ngrp - 1].state) != 0) {
            MGroup *g = &m.grp[m.ngrp++];
            g->ord = ord; g->state = strdup(state);
            g->first = i; g->n = 0; g->total = 0;
            m.bytes += (long)strlen(state) + 1;
        }
        m.grp[m.ngrp - 1].n++;
        m.grp[m.ngrp - 1].total += m.rows[i].count;
        duckdb_free(state); duckdb_free(tok);
    }
    duckdb_destroy_result(&r);
    return m;
}

static void model_free(Model *m) {
    for (long i = 0; i < m->nrows; i++) free(m->rows[i].token);
    for (long i = 0; i < m->ngrp; i++) free(m->grp[i].state);
    free(m->rows); free(m->grp);
}

static int grp_cmp(const void *a, const void *b) {
    const MGroup *x = a, *y = b;
    if (x->ord != y->ord) return x->ord - y->ord;
    return strcmp(x->state, y->state);   /* matches DuckDB's binary collation */
}

static MGroup *model_find(Model *m, int ord, const char *state) {
    MGroup key = { .ord = ord, .state = (char *)state };
    return bsearch(&key, m->grp, (size_t)m->ngrp, sizeof *m->grp, grp_cmp);
}

static void cmd_gen(duckdb_connection con, int k, long max_tokens, const char *seed) {
    if (k < 1 || k > MAX_ORDER) { fprintf(stderr, "order must be 1..%d\n", MAX_ORDER); return; }
    if (max_tokens < 1) max_tokens = 50;
    if (max_tokens > MAX_HISTORY - 64) {   /* every step is a SELECT + INSERT */
        max_tokens = MAX_HISTORY - 64;
        printf("%s(capped at %ld tokens)%s\n", DIM, max_tokens, RESET);
    }

    char **hist = malloc(MAX_HISTORY * sizeof *hist);
    int    hlen = 0;

    /* seed goes through the SAME tokenization as training */
    if (seed && *seed) {
        duckdb_prepared_statement ps;
        duckdb_result r;
        duckdb_prepare(con,
            "SELECT unnest(regexp_extract_all(replace(lower($1), '’', ''''),"
            " '[\\p{L}][\\p{L}'']*'))", &ps);
        duckdb_bind_varchar(ps, 1, seed);
        if (duckdb_execute_prepared(ps, &r) != DuckDBError)
            for (idx_t i = 0; i < duckdb_row_count(&r) && hlen < MAX_ORDER * 4; i++) {
                char *t = duckdb_value_varchar(&r, 0, i);
                hist[hlen++] = strdup(t);
                duckdb_free(t);
            }
        duckdb_destroy_result(&r);
        duckdb_destroy_prepare(&ps);
    }
    if (hlen == 0) hist[hlen++] = strdup("<s>");

    /* bookkeeping row + its id */
    {
        duckdb_prepared_statement ps;
        duckdb_prepare(con,
            "INSERT INTO generation_runs (seed, requested_order, max_tokens)"
            " VALUES ($1,$2,$3)", &ps);
        duckdb_bind_varchar(ps, 1, seed ? seed : "");
        duckdb_bind_int32(ps, 2, k);
        duckdb_bind_int32(ps, 3, (int)max_tokens);
        duckdb_result r;
        duckdb_execute_prepared(ps, &r);
        duckdb_destroy_result(&r);
        duckdb_destroy_prepare(&ps);
    }
    long run_id = query_long(con, "SELECT currval('seq_genrun')");

    double t0 = mu_now_sec();
    Model m = model_load(con);
    char b1[32], b2[32], b3[32];
    printf("%s ┌─ model: %s transitions · %s states · %sB RAM · loaded in %.3fs%s\n",
           DIM, mu_fmt_si((double)m.nrows, b1), mu_fmt_si((double)m.ngrp, b2),
           mu_fmt_si((double)m.bytes, b3), mu_now_sec() - t0, RESET);

    duckdb_appender app;
    if (duckdb_appender_create(con, NULL, "generation_steps", &app) == DuckDBError) {
        fprintf(stderr, "%scannot create appender for generation_steps%s\n", RED, RESET);
        for (int i = 0; i < hlen; i++) free(hist[i]);
        free(hist); model_free(&m);
        return;
    }

    int tokens = 0;
    const char *why = "token limit";
    double t1 = mu_now_sec();
    for (long step = 0; step < max_tokens; step++) {
        char state[BUF];
        MGroup *g = NULL;
        int used = 0;

        /* backoff: longest context we have data for wins */
        for (int ord = (hlen < k ? hlen : k); ord >= 1 && !g; ord--) {
            state[0] = '\0';
            for (int i = hlen - ord; i < hlen; i++) {
                if (i > hlen - ord) strlcat(state, " ", sizeof state);
                strlcat(state, hist[i], sizeof state);
            }
            if ((g = model_find(&m, ord, state)) != NULL) used = ord;
        }
        if (!g) { why = "dead end (state unseen at every order)"; break; }

        /* weighted draw within the group: P(next) = count / total */
        long draw = (long)(rand() / ((double)RAND_MAX + 1) * (double)g->total);
        long idx = g->first;
        while (draw >= m.rows[idx].count) { draw -= m.rows[idx].count; idx++; }
        MRow *row = &m.rows[idx];

        duckdb_append_int32(app, (int32_t)run_id);
        duckdb_append_int32(app, (int32_t)step);
        duckdb_append_varchar(app, state);
        duckdb_append_int8(app, (int8_t)used);
        duckdb_append_int32(app, row->next_id);
        duckdb_append_double(app, (double)row->count / (double)g->total);
        duckdb_append_int32(app, (int32_t)g->n);
        duckdb_appender_end_row(app);

        hist[hlen++] = strdup(row->token);
        if (strcmp(row->token, "</s>") == 0) {
            /* sentence boundary, not a stop: open a fresh <s> context and go on */
            if (hlen >= MAX_HISTORY - 1) { why = "history limit"; break; }
            hist[hlen++] = strdup("<s>");
            continue;
        }
        tokens++;
        if (hlen >= MAX_HISTORY) { why = "history limit"; break; }
    }
    double dt = mu_now_sec() - t1;

    duckdb_appender_destroy(&app);   /* flushes the whole step log in one batch */
    model_free(&m);

    /* long outputs go to a file keyed by run id instead of flooding the console */
    FILE *out = stdout;
    char outpath[64] = "";
    if (tokens > 500) {
        mkdir("output", 0755);
        snprintf(outpath, sizeof outpath, "output/run_%ld.txt", run_id);
        out = fopen(outpath, "w");
        if (!out) {
            fprintf(stderr, "%scannot write %s%s\n", RED, outpath, RESET);
            out = stdout; outpath[0] = '\0';
        }
    }
    int printed = 0;
    for (int i = 0; i < hlen; i++) {
        if (!strcmp(hist[i], "</s>")) { if (printed) fputc('.', out); }
        else if (strcmp(hist[i], "<s>") != 0)
            fprintf(out, "%s%s", printed++ ? " " : "", hist[i]);
        free(hist[i]);
    }
    if (printed) fputc('\n', out);
    if (out != stdout) {
        fclose(out);
        printf("output is %d tokens — full text written to %s%s%s\n",
               tokens, BOLD, outpath, RESET);
    }
    free(hist);
    printf("%s └─ run %ld · order %d · %s tokens · gen %.3fs · %s tok/s · stopped at %s%s\n",
           DIM, run_id, k, mu_fmt_si((double)tokens, b1), dt,
           mu_fmt_si(dt > 0 ? tokens / dt : 0.0, b2), why, RESET);
}

/* ---------------- :stats ---------------- */

static const struct { const char *name; const char *sql; } STATS[] = {
    { "zipf",
      "SELECT token, freq, RANK() OVER (ORDER BY freq DESC) AS rank "
      "FROM vocabulary WHERE token NOT IN ('<s>','</s>') ORDER BY rank LIMIT 30" },
    { "backoff",
      "SELECT order_used, COUNT(*) AS steps,"
      " ROUND(100.0*COUNT(*)/(SELECT COUNT(*) FROM generation_steps),1) AS pct "
      "FROM generation_steps GROUP BY ROLLUP(order_used) ORDER BY order_used NULLS LAST" },
    { "perplexity",
      "SELECT run_id, COUNT(*) AS tokens,"
      " ROUND(-AVG(log2(chosen_prob)),3) AS avg_surprise_bits,"
      " ROUND(pow(2,-AVG(log2(chosen_prob))),2) AS perplexity "
      "FROM generation_steps GROUP BY run_id ORDER BY run_id" },
    { "entropy",
      "WITH p AS (SELECT ord, state_key,"
      "  count::DOUBLE/SUM(count) OVER (PARTITION BY ord,state_key) AS prob"
      "  FROM transitions) "
      "SELECT ord, state_key, COUNT(*) AS branches,"
      " ROUND(-SUM(prob*log2(prob)),3) AS entropy_bits "
      "FROM p GROUP BY ord, state_key HAVING COUNT(*) > 1 "
      "ORDER BY entropy_bits DESC LIMIT 20" },
    { "size",
      "SELECT t.ord, COUNT(*) AS transitions, COUNT(DISTINCT t.state_key) AS states,"
      " format_bytes(SUM(length(t.state_key) + 13)::BIGINT) AS model_size,"
      " (SELECT string_agg(DISTINCT d.name, ', ') FROM training_runs tr"
      "  JOIN documents d ON d.id = tr.document_id WHERE tr.ord = t.ord) AS trained_on "
      "FROM transitions t GROUP BY t.ord ORDER BY t.ord" },
    { "growth",
      "SELECT tr.id AS run, d.name, tr.ord, tr.ngrams_added,"
      " SUM(tr.ngrams_added) OVER (ORDER BY tr.id) AS cumulative_ngrams "
      "FROM training_runs tr JOIN documents d ON d.id = tr.document_id ORDER BY tr.id" },
};
#define N_STATS (sizeof STATS / sizeof *STATS)

static void cmd_stats(duckdb_connection con, const char *name) {
    for (size_t i = 0; i < N_STATS; i++)
        if (strcmp(name, STATS[i].name) == 0) { run_and_print(con, STATS[i].sql); return; }
    fprintf(stderr, "%sunknown stat '%s'%s; available:", RED, name, RESET);
    for (size_t i = 0; i < N_STATS; i++) fprintf(stderr, " %s", STATS[i].name);
    fprintf(stderr, "\n");
}

/* ---------------- :reset / :help / REPL ---------------- */

static const char *RESET_SQL =  /* children first (FK dependency order) */
    "DROP TABLE IF EXISTS generation_steps; DROP TABLE IF EXISTS generation_runs;"
    "DROP TABLE IF EXISTS training_runs; DROP TABLE IF EXISTS transitions;"
    "DROP TABLE IF EXISTS documents; DROP TABLE IF EXISTS vocabulary;"
    "DROP SEQUENCE IF EXISTS seq_vocab; DROP SEQUENCE IF EXISTS seq_doc;"
    "DROP SEQUENCE IF EXISTS seq_trainrun; DROP SEQUENCE IF EXISTS seq_genrun;";

static void help(void) {
    printf("%s:train <file> <order>%s     tokenize <file>, merge n-grams at every order 1..<order>\n"
           "%s:gen <order> [n] [seed…]%s  generate up to n tokens (default 50), optional seed phrase\n"
           "%s:stats <name>%s             zipf | backoff | perplexity | entropy | size | growth\n"
           "%s:reset%s                    drop and recreate the schema (model starts empty)\n"
           "%s:help / :quit%s\n"
           "\n"
           "example session:\n"
           "  :train books.txt 3        train orders 1..3 on books.txt\n"
           "  :gen 3 100 to be or       100 tokens, order-3 backoff, seeded\n"
           "  :stats size               how big the model is per order\n"
           "\n"
           "file paths are relative to the directory markov was started from.\n"
           "the model persists in the database file (default data/db/markov.db;\n"
           "pass another path as the first argument: ./markov mymodel.db).\n",
           BOLD, RESET, BOLD, RESET, BOLD, RESET, BOLD, RESET, BOLD, RESET);
}

int main(int argc, char **argv) {
    srand((unsigned)time(NULL));
    const char *db_path = argc > 1 ? argv[1] : "data/db/markov.db";
    duckdb_database   db;
    duckdb_connection con;

    if (argc <= 1) {   /* default location — make sure the directory exists */
        mkdir("data", 0755);
        mkdir("data/db", 0755);
    }
    if (duckdb_open(db_path, &db) == DuckDBError) {
        fprintf(stderr, "failed to open %s\n", db_path); return EXIT_FAILURE;
    }
    if (duckdb_connect(db, &con) == DuckDBError) {
        fprintf(stderr, "failed to connect\n"); duckdb_close(&db); return EXIT_FAILURE;
    }
    if (db_exec(con, schema_sql)) return EXIT_FAILURE;

    mu_colors_init();
    printf("%smarkov-db v%s%s — model in %s. :help for commands.\n",
           BOLD, MARKOV_VERSION, RESET, db_path);
    int interactive = isatty(STDIN_FILENO);
    char line[BUF];
    while (printf("%smarkov>%s ", CYAN, RESET), fflush(stdout),
           fgets(line, sizeof line, stdin)) {
        line[strcspn(line, "\n")] = '\0';
        /* scripted runs (make demo): echo commands, treat # lines as narration */
        if (!interactive)
            printf("%s%s%s\n", line[0] == '#' ? DIM : BOLD, line, RESET);
        if (line[0] == '#') continue;
        char path[1024], name[64], seed[BUF];
        int k;
        long n;
        if (sscanf(line, ":train %1023s %d", path, &k) == 2) {
            cmd_train(con, path, k);
        } else if (!strncmp(line, ":gen", 4)) {
            n = 50; seed[0] = '\0';
            if (sscanf(line, ":gen %d %ld %[^\n]", &k, &n, seed) >= 2 ||
                sscanf(line, ":gen %d %[^\n]", &k, seed) >= 1)
                cmd_gen(con, k, n, seed);
            else
                fprintf(stderr, "usage: :gen <order> [n] [seed…]\n");
        } else if (!strncmp(line, ":stats", 6)) {
            if (sscanf(line, ":stats %63s", name) == 1) {
                cmd_stats(con, name);
            } else {
                printf("usage: :stats <name> — available:");
                for (size_t i = 0; i < N_STATS; i++) printf(" %s", STATS[i].name);
                printf("\n");
            }
        } else if (!strcmp(line, ":reset")) {
            if (!db_exec(con, RESET_SQL) && !db_exec(con, schema_sql))
                printf("schema reset.\n");
        } else if (!strcmp(line, ":help")) {
            help();
        } else if (!strcmp(line, ":quit") || !strcmp(line, ":q")) {
            break;
        } else if (line[0]) {
            fprintf(stderr, "%sunknown command%s — :help lists them\n", RED, RESET);
        }
    }

    duckdb_disconnect(&con);
    duckdb_close(&db);
    return EXIT_SUCCESS;
}
